name: ConnectorPlugin
version: ${minecraft.plugin.version}
main: de.themoep.connectorplugin.bukkit.BukkitConnectorPlugin
api-version: 1.13
authors: [Phoenix616]
commands:
  connectorplugin:
    description: Connector plugin command
    permission: connectorplugin.command
    usage: /<command> teleport|teleportoplayer|servercommand <server|p:player>|proxyplayercommand <player>|proxycommand <command...>
    aliases:
    - connector
    - connectorcommand
    - connplugin
    - cp