# Plugin debugging
debug: true

# Currently supported types:
# - "plugin_messages" (will not be able to send messages to servers without any players online, messages will be queued)
# - "redis" (does not require any online players)
# - "mqtt" (does not require any online players)
messenger-type: redis

# Redis messenger settings
redis:
  host: localhost
  port: 6379
  db: 0
  timeout: 60
  password: password1
  
# Mqtt messenger settings
mqtt:
  broker-uri: tcp://localhost:1883
  keep-alive: 30
  username: mqttuser
  password: password1